<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2011-05-07 11:03

$extensionClassesPath = t3lib_extMgm::extPath('theaterinfo') . 'Classes/';
return array(
	'tx_theaterinfo_hooks_menu' => $extensionClassesPath . 'Hooks/Menu.php',
);
?>