---
on:
  push:
  workflow_dispatch:

env:
  TYPO3_EXTENSION_KEY: theaterinfo
  MAIN_PHP_VERSION: 8.2

jobs:
  "composer-validate":
    name: "Composer validate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composer
        with:
          php_version: "${{ env.MAIN_PHP_VERSION }}"
      - run: |
          bash .Build/bin/t3_run_tests.sh -s composerValidate -p ${{ env.MAIN_PHP_VERSION }}

  "composer-normalize":
    name: "Composer normalize"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composer
        with:
          php_version: "${{ env.MAIN_PHP_VERSION }}"
      - run: |
          bash .Build/bin/t3_run_tests.sh -s composerNormalize -n -p ${{ env.MAIN_PHP_VERSION }}

  "check-codestyle-codesniffer":
    name: "PHP_CodeSniffer check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composer
        with:
          php_version: "${{ env.MAIN_PHP_VERSION }}"
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ env.MAIN_PHP_VERSION }}"
      - run: |
          bash .Build/bin/t3_check_codestyle.sh PSRTheaterinfo

  "check-codestyle-php-cs-fixer":
    name: "PHP CS Fixer check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composer
        with:
          php_version: "8.1"
      - run: |
          bash .Build/bin/t3_run_tests.sh -s cgl -n -p ${{ env.MAIN_PHP_VERSION }}

  "php-lint":
    name: "PHP linting"
    strategy:
      matrix:
        php_version: ["8.1", "8.2"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composer
        with:
          php_version: ${{ matrix.php_version }}
      - run: |
          bash .Build/bin/t3_run_tests.sh -s lintPhp -p ${{ matrix.php_version }}

  "typo3-scan":
    name: "Scan for deprecated and breaking code using typo3scan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composer
        with:
          php_version: "${{ env.MAIN_PHP_VERSION }}"
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ env.MAIN_PHP_VERSION }}"
      - run: php .Build/bin/typo3scan scan --target 12 .
